### ISSUE TITLE
Using UnityLogger In client init cause Socket to not work properly

### ISSUE THREAD

**Issue by hdjay0129** [heroiclabs/nakama-dotnet#10]
##Description
Using **UnityLogger** causes WebSocketWrapper's constructor to return early because of **Trace** field being false.
https://github.com/heroiclabs/nakama-dotnet/blob/master/src/Nakama/WebSocketWrapper.cs#L92

Here's when there's is no logger provided in **Client** init, it uses **NullLogger** by default. so this Trace variable is true in that case,
-- https://github.com/heroiclabs/nakama-dotnet/blob/master/src/Nakama/WebSocketWrapper.cs#L73

But when UnityLogger is provided. Trace becomes false and causes WebSocketWrapper's constructor to return early.

##Desired
Use **Client's Trace field** when creating webSocket just like Logger. 

##Related Issues
This issue is related to -- https://github.com/heroiclabs/nakama/issues/236

**Comment by novabyte** [comment]
This was solved in https://github.com/heroiclabs/nakama-dotnet/commit/06b88199e23b86b578d33d5bdfae343d38278d36.
