### ISSUE TITLE
TcpClient does not work properly on GoDot v3.4.4 Mono

### ISSUE THREAD

**Issue by JayArrowz** [heroiclabs/nakama-dotnet#106]
Info:
TCP client throwing invalid address error with IPv4 addresses for some reason. This is not recognised as a url `ws://127.0.0.1:7350/ws?lang=en&status=False&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIzZGVlYThhZC0wMTVmLTQyZTktYjdhMS0zN2M3OGY3ZTZmMjkiLCJ1c24iOiJ4cWx0VXRTS25ZIiwiZXhwIjoxNjU3NDgzMTA4fQ.UwMwhtLrK0Yzd4ylNG2MXkC_rRLMOvq2nbZKy7n6xBY` when TCP client is in V6 mode and DualMode = true

https://github.com/heroiclabs/nakama-dotnet/blob/e75097adeeee106949aa51de1140e68e55b12616/Nakama/Ninja.WebSockets/WebSocketClientFactory.cs#L222

Code:
```csharp
var client = new Client("http", "127.0.0.1", 7350, "defaultkey", HttpRequestAdapter.WithGzip());
var socket = Socket.From(client);
var userSession = await client.AuthenticateCustomAsync(Guid.NewGuid().ToString());
await socket.ConnectAsync(userSession);
```

Original Error:
![image](https://user-images.githubusercontent.com/49910176/178156633-b056d1fe-97ab-4f55-9fe6-905129e05f11.png)

Versions:
GoDot v3.4.4 
GoDot .NET SDK v3.3.0
Net Framework v 4.7.2
OS Win 11

Extra issues relating to this:
https://github.com/godotengine/godot/issues/58458

To fix this stop IPv6 support:
![image](https://user-images.githubusercontent.com/49910176/178156703-2dcc6726-1c42-4502-aa54-08bbadeaf7ca.png)

**Comment by lugehorsam** [comment]
Hey @JayArrowz, thanks for filing the issue. I don't think it's a Nakama issue per se because it's up to Godot's Mono distribution to support Dual Mode. 

Is there anything you'd like to see on our end here?

**Comment by JayArrowz** [comment]
@lugehorsam 
Is it possible we can add a flag to be able to set the TCP sockets address family and dual socket mode?

**Comment by JayArrowz** [comment]
@lugehorsam can confirm the WebsocketStdLibAdapter works with godot mono 👍

**Comment by lugehorsam** [comment]
Thanks for testing @JayArrowz we'll document this in the README when we get the chance.

**Comment by Atlinx** [comment]
Hey all, sorry to ressurect this but what was the solution to fixing this? What code should I write instead of `var socket = Socket.From(client);`.?
