### ISSUE TITLE
HttpRequestAdapter failed to handle non json error response 

### ISSUE THREAD

**Issue by oshribin** [heroiclabs/nakama-dotnet#109]
We encounter an issue where the server (probably the underlying load-balancer) failed with 502 server error which returned as a plain HTML.

```
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>
```

In such case this piece of code will result with 
```System.NullReferenceException: Object reference not set to an instance of an object``` as the result of `contents.FromJson<Dictionary<string, object>>()` 
 is null.

https://github.com/heroiclabs/nakama-dotnet/blob/42493a630e7870eca53309d249ac39a8bc8a0154/Nakama/HttpRequestAdapter.cs#L100-L102

**Comment by lugehorsam** [comment]
@oshribin can you share details about your underlying infrastructure? Are you using Heroic Cloud?

**Comment by oshribin** [comment]
Yes,
We are using Heroic Cloud.
High-Availability Enabled.
