### ISSUE TITLE
Nakama service cannot work behind a reverse proxy

### ISSUE THREAD

**Issue by h3ph4est7s** [heroiclabs/nakama-dotnet#116]
The nakama service cannot run behind a reverse proxy as the client does not accept a path to the connection URI. I dont see why this is not possible from the moment nakama uses websockets and HTTP API calls. The added value of this is also security filtering from broadly available WAFs and other security solutions. This is relevant to https://github.com/heroiclabs/nakama-dotnet/issues/17

**Comment by novabyte** [comment]
@h3ph4est7s The reason this has not been added is simply because it's not been needed so far. All game teams that we work with and those who use Nakama typically deploy it with a dedicated sub-domain. Please open a pull request.
