### ISSUE TITLE
GetUsersAsync preserve order?

### ISSUE THREAD

**Issue by teamclouday** [heroiclabs/nakama-dotnet#133]
Hey I was trying to get user display names by calling `IClient.GetUsersAsync`.\
The problem is that the returned users does not preserve the order of the input `ids`, instead it is the same for every client.\
Would it be better to preserve order by default?

**Comment by novabyte** [comment]
@teamclouday Most of the APIs which send batch inputs to the server do not guarantee that the returned results are ordered by the input sequence. I would recommend you alphanumerically sort your input IDs and then sort the returned `IList<IApiUser>` by the same user IDs. This way you can make sure your inputs and outputs are synced in the way you require.

I do wonder whether in general though you'd be better off with some kind of simple map-based cache for `IApiUser` types (probably with a capacity based eviction policy). This way you get the users you want by ID from the cache and don't really have to think about the synchronization of input and output order of the data. Hope this helps.

**Comment by teamclouday** [comment]
Hey @novabyte thanks for your response! Good to know how the APIs work.\
And yes that's exactly what I implemented later. I built a map from the returned `IApiUser` that maps user IDs to user names, and then cached the information.\
Closing
