### ISSUE TITLE
Wrong presence

### ISSUE THREAD

**Issue by flametime** [heroiclabs/nakama-dotnet#155]
Not all players connected to room 

<img width="450" alt="image" src="https://github.com/heroiclabs/nakama-dotnet/assets/65140665/dedc52cf-f25c-4489-b52b-73c973b8e16a">

<img width="480" alt="image" src="https://github.com/heroiclabs/nakama-dotnet/assets/65140665/c24ca0ae-96dc-4f0a-92c9-8231f395ef20">

**Comment by flametime** [comment]
<img width="573" alt="image" src="https://github.com/heroiclabs/nakama-dotnet/assets/65140665/46948fb3-5004-4a95-a090-93390d2d2fe0">

Am i doing something wrong?

**Comment by novabyte** [comment]
@flametime can you paste what you see from `match.Presences`, `match.Self`, `presenceEvent.Joins`, and `presenceEvent.Leaves`?
