### ISSUE TITLE
Nakama client cannot connect to a Nakama service running after a loadbalancer.

### ISSUE THREAD

**Issue by truonglvx** [heroiclabs/nakama-dotnet#17]
When the client connect to a Nakama service that running after a loadbalancer using a path-based routing such as api.example.com/nakama, it failed.

**Comment by mofirouz** [comment]
> The error is NullReferenceException, because the Client object cannot instantiate.

**Comment by novabyte** [comment]
I'm going to triage this issue. Please reopen @truonglvx if you can provide more details.

**Comment by h3ph4est7s** [comment]
a root path parameter to this line https://github.com/heroiclabs/nakama-dotnet/blob/ccc9f351522511f4cd8bfc870866b2bd483c0599/Nakama/Client.cs#L115 is probably going to solve this problem.
