### ISSUE TITLE
Throw a reason along with OnDisconnect Event of Socket

### ISSUE THREAD

**Issue by hdjay0129** [heroiclabs/nakama-dotnet#18]
#Description 
Currently OnDisconnect Event of WebSocketWrapper doesn't have a reason along with it to know why OnDisconnect Event got triggered from socket.

OnError is also triggered when Socket is no logger connected and has an Exception Object with it which has info about disconnection. But OnError is also called on other Errors like SendMatchState error. So OnError can't be used to only detect any disconnection related reasons.

#Desired
OnDisconnect Event should have an exception object along with it to help developers to know what exactly caused Socket's OnDisconnect Event.

**Comment by novabyte** [comment]
@hdjay0129 We've pushed up a new release of the .NET client. Please experiment with it and re-open this issue with specific exception reasons you think would be better sent to the socket closed event rather than the error event receiver.
