### ISSUE TITLE
C# - Maximum time to join a match

### ISSUE THREAD

**Issue by albermotion** [heroiclabs/nakama-dotnet#24]
It could be interesting to be able to set a timeout when trying to join a match.
This way we could listen to an event similar to `ReceivedMatchmakerMatched` when the max time has passed and thus handle what to do next (maybe use an AI to play against the player or send a message to the player that no matches were found).

This might be added as an optional parameter when calling `AddMatchmakerAsync` from the created socket.

**Comment by novabyte** [comment]
I'll close this issue because it has been inactive for over 6 months. Nakama has had interval-based matchmaker behaviour for quite a while now which should cover your use case.
