### ISSUE TITLE
IChannelPresenceEvent and IApiChannelMessage has empty room name

### ISSUE THREAD

**Issue by thegoldenmule** [heroiclabs/nakama-dotnet#25]
#### Description

Submitting after discussion with @novabyte on gitter.

In short, the `RoomName` property is always blank on presence events.

#### Reproduction Steps

We have the server automatically join users to chat rooms on session start. Our plugin can then disallow all channel join requests. In this way, we lock down chat, so that users aren't joining rooms themselves.

To do this, we do:

```
ok, err := nk.StreamUserJoin(2, "", "", roomName, userId, sessionId, false, true, "")
```
The client receives a `IChannelPresenceEvent`, but the `RoomName` property is empty. Here we log out the event:

```
ChannelPresenceEvent(ChannelId='2...general', Joins=[UserPresence(Persistence=True, SessionId='3b640e8c-2a5d-4663-9080-16f595337e47', Status='', Username='TJNEVGUWOO', UserId='7cab4c19-80c6-4528-af51-a0db322adceb')], Leaves=[], RoomName='', GroupId='', UserIdOne='', UserIdTwo='')
```

#### Expected Results

A ChannelPresenceEvent with a populated RoomName.

**Comment by novabyte** [comment]
@thegoldenmule This is fixed in https://github.com/heroiclabs/nakama/commit/9843a76f80b9af6cc26eade53e51dff3e942c1ef and will be part of the next server release.
