### ISSUE TITLE
Rejected rpc nullreference

### ISSUE THREAD

**Issue by dre0dru** [heroiclabs/nakama-dotnet#38]
Hello! Found an issue with rejected rpc.
Recent changes are "return decoded error message rather than error dictionary when rpc fails".
But **IHttpAdapterExtensions** was not updated to handle error as **not** dictionary.
So when ```CopyErrorDictionary()``` method is called it tries to cast object as ```Dictionary<string, object>``` and than iterates over it which causes ```NullReferenceException```:
```
 var errDict = decodedResponse["error"] as Dictionary<string, object>;

            foreach (KeyValuePair<string, object> keyVal in errDict)
            {
                e.Data[keyVal.Key] = keyVal.Value;
            }
```
![image](https://user-images.githubusercontent.com/17127480/92587750-babf2680-f2a0-11ea-8bd6-2c694033fa5c.png)

**Comment by lugehorsam** [comment]
@dre0dru could you share your server-side RPC code?
