### ISSUE TITLE
Unity WebSockets - InvalidOperationException, task already complete exception

### ISSUE THREAD

**Issue by zfand** [heroiclabs/nakama-dotnet#41]
Hi Nakama,

 I'm seeing this exception in my game on production for iOS/Android. I haven't been able to to figure out where it's coming from exactly but from looking at the code I believe there it's happening in the callback from Socket.cs calling `SetResult` instead of `TrySetResult` [here](https://github.com/heroiclabs/nakama-dotnet/blob/5a7ae9e28b73b2b0dbb48b00e5acd7f215b9c028/src/Nakama/Socket.cs#L181).

Stacktrace:
``` 
InvalidOperationException An attempt was made to transition a task to a final state when it had already completed. 
    <00000000000000000000000000000000> System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[TResult].Create()
    <00000000000000000000000000000000> Nakama.Ninja.WebSockets.PongEventArgs..ctor(System.ArraySegment`1[T] payload)
    <00000000000000000000000000000000> System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object stateMachine)
    <00000000000000000000000000000000> System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx)
    <00000000000000000000000000000000> System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
    <00000000000000000000000000000000> System.Threading.ThreadPoolWorkQueue.Dispatch()
    unknown System.UnhandledExceptionEventHandler:Invoke(Object, UnhandledExceptionEventArgs)
```

**Comment by lugehorsam** [comment]
Thanks @zfand, we'll take a look.

**Comment by lugehorsam** [comment]
@zfand I think I agree that we'll want to modify that to `TrySetResult` -- but I wanted to ask what made you suspect it was coming from there? The stack trace is tricky because the `PongEventArgs` constructor is not doing anything meaningful.
