### ISSUE TITLE
ListFriendsAsync function returns empty value with FacebookId key

### ISSUE THREAD

**Issue by Ersan45** [heroiclabs/nakama-dotnet#48]
## Description
When client calls ListFriendsAsync API function, result has empty value with FacebookId key.

## Steps to Reproduce
1. Authenticate user.
2. Call ListFriendsAsync function

## Expected Result

Result must contain value with FacebookId key
## Actual Result

Result does not contain value with FacebookId key
## Context

- [ ] Unity

## Your Environment

- Nakama: 2.15.0
- Database:19.2.5

**Comment by lugehorsam** [comment]
@Ersan45 thanks for filing this issue -- I've transferred it to the nakama dot-net repository and will address it after the holidays.

**Comment by lugehorsam** [comment]
@Ersan45 `ListFriendsAsync` returns a collection of `IApiFriend`. Each `IApiFriend` has an attached `User` from which you can access a `FacebookId`. Are you saying some of the `FacebookId` values are empty? And you're sure those users have authenticated via Facebook?

**Comment by Ersan45** [comment]
@lugehorsam All the ```FacebookId```s are empty. Yes I am sure that they are all authenticated via Facebook.

**Comment by lugehorsam** [comment]
@Ersan45 this is resolved in our new Nakama 3.0 release.
