### ISSUE TITLE
Socket implementation replaces complete path before sending to adapter

### ISSUE THREAD

**Issue by OtterBlitzStudio** [heroiclabs/nakama-dotnet#49]
Hey,

https://github.com/heroiclabs/nakama-dotnet/blob/9c9716eae213ed5dc56912bb7914d7a217cb43ab/src/Nakama/Socket.cs#L187
am I right that this line replaces the complete path?

So if I have "https://my-domain.com/nakama-server" as my _basURI I send "https://my-domain.com/ws?..." to the adapter instead of "https://my-domain.com/nakama-server/ws?...", right?

**Comment by novabyte** [comment]
@OtterBlitzStudio It's not recommended to run the server from a path within a domain. You should run it from the root of the domain and use subdomains to host parts of the application. For example mygame.com and gs.mygame.com. This works very well with a wildcard SSL certificate and the server already correctly responds to CORS requests to allow for web-based games.

In your example the socket endpoint for the adapter would be: "https://my-domain.com/nakama-server/ws".
