### ISSUE TITLE
Task canceled when trying to send messages bigger than 3900 size

### ISSUE THREAD

**Issue by cata0309** [heroiclabs/nakama-dotnet#63]
I receive this
```Unhandled exception. System.Threading.Tasks.TaskCanceledException: A task was canceled. at Nakama.Socket.WriteChatMessageAsync(String channelId, String content)```
^ when trying to send messages over 3900 chars long
What should be the problem and how can I fix it?

**Comment by novabyte** [comment]
@cata0309 This is not an issue with the .NET client SDK. You should configure the `--socket.max_message_size_bytes` option in the server to fit what you need. By default the value is ~4KB. https://heroiclabs.com/docs/install-configuration/
