### ISSUE TITLE
Client's Timeout value is never used within WebSocketWrapper for ConnectTimout.

### ISSUE THREAD

**Issue by hdjay0129** [heroiclabs/nakama-dotnet#8]
## Description
Timeout field of Client is currently not being used while creating WebSocketWrapper object.
So ConnectTimeout is set to default value of 5 seconds.

## Desired
WebSocketWrapper's ConnectTimeout should use Client's Timeout value.

**Comment by mofirouz** [comment]
This Is fixed with your own PR 😬 (63bc5fc4741345648366c45cce3637b5e8cb0ad9)
