### ISSUE TITLE
C# - Socket from Unity SDK does not timeout from ping/pongs

### ISSUE THREAD

**Issue by igorshostakdev** [heroiclabs/nakama-dotnet#92]
I have just started using Nakama (3.3.0) in one of the mobile projects and stumbled across a problem with a socket connection. Everything seems to be working fine on a target device, but when it comes to testing in the editor, things start to get strange. I am using this code to keep track of the connected state of the socket:

```
var uri = new Uri("http://example.com:7350");

var client = new Client(uri.Scheme, uri.Host, uri.Port, "defaultkey");

var session = await client.AuthenticateDeviceAsync(SystemInfo.deviceUniqueIdentifier);

var socket = Socket.From(client, new WebSocketAdapter(3, 2));

socket.Connected += () =>
{
	UnityEngine.Debug.LogError("Connected");
};

socket.Closed += () =>
{
	UnityEngine.Debug.LogError("Closed");
};

await socket.ConnectAsync(session);
```
Then while connected I just unplug my laptop from the Internet, count around 3 seconds and wait for the socket to disconnect. The problem is that nothing happens for around 15-20 seconds and only after that the message “Closed” appears. I am developing stuff in Unity 2021.2.8f1 When it comes to the server, I am running Nakama 3.10.0+ac9a4ccd

My best guess was that something does not “click” in WebSocketAdapter. I have found out that the websocket itself gets closed with CloseSent when PingPongManager sets it after the connection is lost. But for some reason this state does not get propagated to the Closed event of WebSocketAdapter.

**Comment by novabyte** [comment]
Fixed in https://github.com/heroiclabs/nakama-dotnet/commit/9a5d17fab7435d0f59818464f50211ac8aeffb9b.
