### ISSUE TITLE
SocketException when connecting a socket

### ISSUE THREAD

**Issue by dresswithpockets** [heroiclabs/nakama-dotnet#93]
Running a local Nakama server, I'm able to connect and authenticate a session normally. When calling `ISocket.ConnectAsync`, however, I get an exception resembling:

```
System.Net.Sockets.SocketException (0x80004005): The operation completed successfully.

  at System.Net.Sockets.Socket..ctor (System.Net.Sockets.AddressFamily addressFamily, System.Net.Sockets.SocketType socketType, System.Net.Sockets.ProtocolType protocolType) [0x00068] in <5307bcb359e140d4b454b70b3ff646a0>:0 
  at System.Net.Sockets.TcpClient.initialize () [0x00000] in <5307bcb359e140d4b454b70b3ff646a0>:0 
  at System.Net.Sockets.TcpClient..ctor (System.Net.Sockets.AddressFamily family) [0x00046] in <5307bcb359e140d4b454b70b3ff646a0>:0 
  at Nakama.Ninja.WebSockets.WebSocketClientFactory.GetStream (System.Guid loggingGuid, System.Boolean isSecure, System.Boolean noDelay, System.String host, System.Int32 port, System.Threading.CancellationToken cancellationToken) [0x0001b] in <ec226df74c0d4cc6b97fe5f07a3bd598>:0 
  at Nakama.Ninja.WebSockets.WebSocketClientFactory.ConnectAsync (System.Uri uri, Nakama.Ninja.WebSockets.WebSocketClientOptions options, System.Threading.CancellationToken token) [0x000e3] in <ec226df74c0d4cc6b97fe5f07a3bd598>:0 
  at Nakama.WebSocketAdapter.ConnectAsync (System.Uri uri, System.Int32 timeout) [0x00140] in <ec226df74c0d4cc6b97fe5f07a3bd598>:0 
```

Occasionally the message will say "Attempt to access invalid address", instead of "The operation completed successfully". The stacktrace is otherwise identical.

Connect code:
```cs
Socket.ConnectAsync(Session, AppearOnline, ConnectionTimeout)
    .OnSuccess(_ =>
    {
        GD.Print("Socket connection successfully established.");
        EmitSignal(nameof(SocketConnected), this);
    })
    .OnError(t =>
    {
        GD.PushError($"There was an error authenticating a session: {t.Exception}");
        EmitSignal(nameof(SocketConnectionError), this);
    });
```

`OnSuccess` and `OnError` are defined [here](https://gist.github.com/dresswithpockets/0e9dc476c8d5833cff76b06a547046b8#file-taskextensions-cs).

The docker-compose file im using to execute a local nakama server is defined [here](https://gist.github.com/dresswithpockets/0e9dc476c8d5833cff76b06a547046b8#file-nakama-docker-compose-yml).

I'm on Windows 10 x64, using .NET 6 SDK. The project is configured for .NET Framework 4.7.2/Mono.Net Compatibility. It is a Godot project.

**Comment by novabyte** [comment]
@dresswithpockets What arguments do you pass through to configure the socket when it's created? Do you use `"localhost"` or an IP address as the host address?

**Comment by dresswithpockets** [comment]
I've tried both `127.0.01` and `localhost` @novabyte

**Comment by dresswithpockets** [comment]
Just in case this might have been a funny DNS issue with docker, I tried it by running the nakama server outside of docker, and that also resulted in the same error.

@novabyte have any idea what might be going on here?

**Comment by novabyte** [comment]
@dresswithpockets Thanks for the update. A couple of notes on why we have the two adapters:

- `WebSocketAdapter` - Uses `Ninja.WebSockets` as the base network subsystem. We use this for Unity engine compatibility because there's a couple of different Mono runtime bugs which have so far never been resolved which prevents us from using the adapter below.
- `WebsocketWasmAdapter` - Uses `System.Net.ClientWebsocket` from the .NET standard library. This was recently added for a Blazor project (WASM) but I will rename the adapter to be `WebSocketStdlibAdapter` because its not WASM specific.

Hope that helps. Keep an eye out for the rename which will be part of the next release.

**Comment by dresswithpockets** [comment]
Ah, interesting. If those bugs are apart of Mono, then wouldn't they carry over to Godot, since Godot uses Mono? Or is it specific to the version of Mono that Unity uses? @novabyte

**Comment by novabyte** [comment]
@dresswithpockets Unity uses their own fork of Mono runtime with patches of their own but also without patches which have been resolved in the main branch. It's a couple of patches from the main branch which historically weren't carried over into Unity's fork. I think Godot likely uses the main branch of Mono runtime.

**Comment by novabyte** [comment]
@dresswithpockets I think your issue is resolved as far as can be handled by the Unity client. The rest depends on Godot Mono support to be improved as needed. I'll close this issue.
