### ISSUE TITLE
Import this in a Godot(c#) mono engine ?

### ISSUE THREAD

**Issue by D4vid2012** [heroiclabs/nakama-dotnet#98]
Is there a way to do this ? I'm actually struggling with this..

**Comment by lugehorsam** [comment]
Hey @D4vid2012 yes we support usage in Godot with either the C# or Godot clients. How are you importing the .dll? We recommend doing it through Nuget.

**Comment by D4vid2012** [comment]
Hello, I downloaded the client and build it from the source as explained but I don't know how to "merge" it with my godot project. I am not very experimented in this, can you please show me how to this correctly through Nuget ?

**Comment by lugehorsam** [comment]
@D4vid2012 does your Godot project have a `.csproj` file? If so, you should just need to add the following to it underneath the `Project` tag:

```
    <ItemGroup>
      <PackageReference Include="NakamaClient" Version="3.3.0" />
    </ItemGroup>
```

**Comment by D4vid2012** [comment]
I did it, what do I have to import into my project now ? I get two Nakama.dll, one located in bin > net46 and the other in bin > netstandard2.0

**Comment by lugehorsam** [comment]
@D4vid2012 I think you have what you need from us, for any further steps definitely check out the Godot documentation.

**Comment by D4vid2012** [comment]
Okay thank you !
